const brandConfig = [
  {
    title: "Latvenergo",
    searchNames: ["latvenergo"],
    accountNames: ["Latvenergo"],
    brandFile: "./brandTweets/latvenergo.json",
    peopleTweets: "./peopleTweets/latvenergo.json",
  },
  {
    title: "Rimi",
    searchNames: [
      "rimi",
      "rimčik",
      "rimčiks",
      "rikčika",
      "rimčikam",
      "rimčiku",
      "rimčikā",
      "rimčiki",
      "rimčikiem",
      "rimčikus",
      "rimčikos",
    ],
    accountNames: ["MansRimi", "RimiLatvija"],
    brandFile: "./brandTweets/rimi.json",
    peopleTweets: "./peopleTweets/rimi.json",
  },
  {
    title: "Maxima",
    searchNames: [
      "maxima",
      "maximas",
      "maximai",
      "maximu",
      "maximā",
      "maksima",
      "maksimas",
      "maksimai",
      "maksimu",
      "maksimā",
      "maximām",
      "maximās",
      "maksimām",
      "maksimās",
    ],
    accountNames: ["maximaveikals"],
    brandFile: "./brandTweets/maxima.json",
    peopleTweets: "./peopleTweets/maxima.json",
  },
  {
    title: "Swedbank",
    searchNames: [
      "swedbank",
      "swedbanka",
      "swedbankas",
      "swedbankai",
      "swedbanku",
      "swedbankā",
      "swedbankām",
      "swedbankās",
    ],
    accountNames: ["SwedbankLatvia"],
    brandFile: "./brandTweets/swedbank.json",
    peopleTweets: "./peopleTweets/swedbank.json",
  },
  {
    title: "Latvijas Mobilais Telefons",
    searchNames: [
      "latvijas mobilais telefons",
      "lmt",
      "latvijas mobilā telefona",
      "latvijas mobilām telefonam",
      "latvijas mobilo telefonu",
      "latvijas mobilā telefonā",
    ],
    accountNames: ["mansLMT"],
    brandFile: "./brandTweets/lmt.json",
    peopleTweets: "./peopleTweets/lmt.json",
  },
  {
    title: "TET",
    searchNames: ["tet"],
    accountNames: ["mans_tet"],
    brandFile: "./brandTweets/tet.json",
    peopleTweets: "./peopleTweets/tet.json",
  },
  {
    title: "Latvijas gāze",
    searchNames: [
      "latvijas gāze",
      "latvijas gāzes",
      "latvijas gāzei",
      "latvijas gāzi",
      "latvijas gāzē",
    ],
    accountNames: ["ASLatvijasGaze"],
    brandFile: "./brandTweets/lg.json",
    peopleTweets: "./peopleTweets/lg.json",
  },
  {
    title: "Tele2",
    searchNames: ["tele2"],
    accountNames: ["Tele2Latvia"],
    brandFile: "./brandTweets/tele2.json",
    peopleTweets: "./peopleTweets/tele2.json",
  },
  {
    title: "Air Baltic Corporation",
    searchNames: ["air baltic", "airBaltic"],
    accountNames: ["airBaltic"],
    brandFile: "./brandTweets/airbaltic.json",
    peopleTweets: "./peopleTweets/airbaltic.json",
  },
  {
    title: "Olympic Casino",
    searchNames: ["olympic casino", "olympic"],
    accountNames: ["OCasino"],
    brandFile: "./brandTweets/olympic.json",
    peopleTweets: "./peopleTweets/olympic.json",
  },
  {
    title: "SEB Banka",
    searchNames: [
      "seb banka",
      "seb",
      "seb bankas",
      "seb bankai",
      "seb banku",
      "seb bankā",
      "seb bankām",
      "seb bankās",
    ],
    accountNames: ["SEB_Latvia"],
    brandFile: "./brandTweets/seb.json",
    peopleTweets: "./peopleTweets/seb.json",
  },
  {
    title: "Grindeks",
    searchNames: [
      "grindeks",
      "grindeksa",
      "grindeksam",
      "grindeksu",
      "grindeksā",
    ],
    accountNames: ["AS_Grindeks"],
    brandFile: "./brandTweets/grindeks.json",
    peopleTweets: "./peopleTweets/grindeks.json",
  },
  {
    title: "Citadele Banka",
    searchNames: [
      "citadele banka",
      "citadele",
      "citadele bankas",
      "citadele bankai",
      "citadele banku",
      "citadele bankā",
      "citadele bankām",
      "citadele bankās",
    ],
    accountNames: ["Citadele"],
    brandFile: "./brandTweets/citadele.json",
    peopleTweets: "./peopleTweets/citadele.json",
  },
  {
    title: "Bite",
    searchNames: ["bite", "bites", "bitei", "bitē"],
    accountNames: ["Bitelv"],
    brandFile: "./brandTweets/bite.json",
    peopleTweets: "./peopleTweets/bite.json",
  },
  {
    title: "Drogas",
    searchNames: ["drogas", "drogās", "drogām"],
    accountNames: ["DrogasLatvija"],
    brandFile: "./brandTweets/drogas.json",
    peopleTweets: "./peopleTweets/drogas.json",
  },
  {
    title: "Depo DIY",
    searchNames: ["depo"],
    accountNames: [],
    brandFile: "./brandTweets/depo.json",
    peopleTweets: "./peopleTweets/depo.json",
  },
  {
    title: "Cirkle K",
    searchNames: ["circle k", "cirklek"],
    accountNames: ["CircleKLatvija"],
    brandFile: "./brandTweets/circlek.json",
    peopleTweets: "./peopleTweets/circlek.json",
  },
  {
    title: "Latvijas Balzams",
    searchNames: [
      "latvijas balzams",
      "latvijas balzama",
      "latvijas balzamam",
      "latvijas balzamu",
      "latvijas balzamā",
      "latvijas balzami",
      "latvijas balzamiem",
      "latvijas balzamus",
      "latvijas balzamos",
    ],
    accountNames: ["LBveikali"],
    brandFile: "./brandTweets/lb.json",
    peopleTweets: "./peopleTweets/lb.json",
  },
  {
    title: "Optibet",
    searchNames: [
      "optibet",
      "optibets",
      "optibeta",
      "optinetam",
      "optibetu",
      "optibetā",
    ],
    accountNames: ["OptibetLatvija"],
    brandFile: "./brandTweets/optibet.json",
    peopleTweets: "./peopleTweets/optibet.json",
  },
  {
    title: "Evolution",
    searchNames: [
      "evolution latvia",
      "evolution",
      "evolution gaming",
      "evolutiona",
      "evolutionam",
      "evolutionu",
      "evolutionā",
    ],
    accountNames: ["Evo_global"],
    brandFile: "./brandTweets/evolution.json",
    peopleTweets: "./peopleTweets/evolution.json",
  },
];

module.exports = { brandConfig };
